import os
import shutil

os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.Adapter.SIMLVLCRemote.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ChatInterfaceWeb.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.exe.config")
shutil.rmtree("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\WebAssets", True)
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\HttpMultipartParser.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.AspNet.SignalR.Core.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.Cors.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.Diagnostics.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.FileSystems.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.Host.HttpListener.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.Hosting.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.Security.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Microsoft.Owin.StaticFiles.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Newtonsoft.Json.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Owin.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Sprache.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\System.Net.Http.Formatting.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\System.Web.Cors.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\System.Web.Http.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\System.Web.Http.Owin.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ICANCOMPREHEND.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ICANCOMPREHEND.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ICANCOMPREHEND.Host.exe.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\CameraConfigurationList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ICANSEE.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ICANSEE.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.ICANSEE.Host.exe.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICANSEE.AlgorithmsDescriptionList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICANSEE.ComputeDeviceList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICANSEE.PresetDescriptionList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICANSEEDrwReplacementConfiguration.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Jint.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\RestSharp.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.SIMLHub.dll")
shutil.rmtree("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\SIMLHubPlugins", True)
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.Bot.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.EmotionML.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.Log.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.Oryzer.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.Utilities.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.VA.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\Syn.WordNet.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.VLCRemote.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.VLCRemote.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC_Executables - Copy\\ICAN.SIC.Plugin.VLCRemote.Host.exe.config")
