import os
import shutil

os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.Adapter.SIMLVLCRemote.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.ChatInterfaceWeb.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.exe")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.exe.config")
shutil.rmtree("J:\\Project ICAN\\ICAN.SIC_Executables\\WebAssets", True)
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.AspNet.SignalR.Core.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.Cors.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.Diagnostics.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.FileSystems.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.Host.HttpListener.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.Hosting.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.Security.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Microsoft.Owin.StaticFiles.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Newtonsoft.Json.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Owin.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\System.Net.Http.Formatting.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\System.Web.Cors.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\System.Web.Http.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\System.Web.Http.Owin.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.ICANSEE.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.ICANSEE.Host.exe")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.SIMLHub.dll")
shutil.rmtree("J:\\Project ICAN\\ICAN.SIC_Executables\\SIMLHubPlugins", True)
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Jint.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.Bot.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.EmotionML.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.Log.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.Oryzer.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.Utilities.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.VA.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\Syn.WordNet.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.VLCRemote.dll")
os.remove("J:\\Project ICAN\\ICAN.SIC_Executables\\ICAN.SIC.Plugin.VLCRemote.Host.exe")
