import os
import shutil

os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.Adapter.SIMLVLCRemote.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.Adapter.SIMLVLCRemote.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ChatInterfaceWeb.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ChatInterfaceWeb.dll.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.exe.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ChatInterfaceWeb.Host.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ChatInterfaceWeb.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Sprache.pdb")
shutil.rmtree("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\WebAssets", True)
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\HttpMultipartParser.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.AspNet.SignalR.Core.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.Cors.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.Diagnostics.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.FileSystems.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.Host.HttpListener.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.Hosting.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.Security.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Microsoft.Owin.StaticFiles.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Newtonsoft.Json.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Owin.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Sprache.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\System.Net.Http.Formatting.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\System.Web.Cors.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\System.Web.Http.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\System.Web.Http.Owin.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANGEOLOCATE.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANGEOLOCATE.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANGEOLOCATE.Host.exe.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANGEOLOCATE.Host.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANGEOLOCATE.pdb")
shutil.rmtree("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\GeoResources", True)
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\GeoSharp.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\GeoSharp.dll.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\GeoSharp.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\CameraConfigurationList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANSEE.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANSEE.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANSEE.Host.exe.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANSEE.Host.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.ICANSEE.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICANSEE.AlgorithmsDescriptionList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICANSEE.ComputeDeviceList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICANSEE.PresetDescriptionList.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICANSEEDrwReplacementConfiguration.json")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Jint.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\RestSharp.dll")
shutil.rmtree("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\SIMLHubPlugins", True)
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.Bot.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.EmotionML.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.Log.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.Oryzer.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.Utilities.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.VA.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\Syn.WordNet.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.VLCRemote.dll")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.VLCRemote.Host.exe")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.VLCRemote.Host.exe.config")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.VLCRemote.Host.pdb")
os.remove("D:\\Projects\\ICAN\\ICAN.SIC\\bin\\Debug\\ICAN.SIC.Plugin.VLCRemote.pdb")
